In [1]:
import os
import pandas as pd

In [2]:
datas = [x for x in os.listdir() if "results_" in x and ".xlsx" in x]
datas
datas = ["results v02.xlsx", "all_results.xlsx"]
datas = ["results v03.xlsx", "results_1125205844.xlsx"]
datas = ["results v04.xlsx", "results_1128130656.xlsx"]

In [3]:
dfs = []
for data in datas:
    dfs.append(pd.read_excel(data, index_col=0, header=[0,1]))

all_data = pd.concat(dfs, ignore_index=True)

In [4]:
all_data[all_data[("Graph", "name")] == "graphs/0004_250.graphml"]

                        Graph              Exhaustive                  \
                         name  n  m weight       #ops      time #sols
947   graphs/0004_250.graphml  4  1   13.0       70.0  0.000023  16.0
948   graphs/0004_250.graphml  4  1   13.0       70.0  0.000023  16.0
949   graphs/0004_250.graphml  4  1   13.0       70.0  0.000023  16.0
950   graphs/0004_250.graphml  4  1   13.0       70.0  0.000023  16.0
951   graphs/0004_250.graphml  4  1   13.0       70.0  0.000023  16.0
952   graphs/0004_250.graphml  4  1   13.0       70.0  0.000023  16.0
953   graphs/0004_250.graphml  4  1   13.0       70.0  0.000023  16.0
954   graphs/0004_250.graphml  4  1   13.0       70.0  0.000023  16.0
955   graphs/0004_250.graphml  4  1   13.0       70.0  0.000023  16.0
956   graphs/0004_250.graphml  4  1   13.0       70.0  0.000023  16.0
957   graphs/0004_250.graphml  4  1   13.0       70.0  0.000023  16.0
958   graphs/0004_250.graphml  4  1   13.0       70.0  0.000023  16.0
959   graphs/0004_250.graphml  4  1   13.0       70.0  0.000023  16.0
960   graphs/0004_250.graphml  4  1   13.0       70.0  0.000023  16.0
961   graphs/0004_250.graphml  4  1   13.0       70.0  0.000023  16.0
962   graphs/0004_250.graphml  4  1   13.0       70.0  0.000023  16.0
963   graphs/0004_250.graphml  4  1   13.0       70.0  0.000023  16.0
964   graphs/0004_250.graphml  4  1   13.0       70.0  0.000023  16.0
965   graphs/0004_250.graphml  4  1   13.0       70.0  0.000023  16.0
966   graphs/0004_250.graphml  4  1   13.0       70.0  0.000023  16.0
5847  graphs/0004_250.graphml  4  1   13.0       70.0  0.000023  16.0

     Heuristic                  ... Random Solutions (MS: 100)            \
          #ops      time #sols  ...                        it. prec./it.
947         28  0.000008     1  ...                       52.0  0.153846
948         28  0.000008     1  ...                        NaN       NaN
949         28  0.000008     1  ...                        NaN       NaN
950         28  0.000008     1  ...                       51.0  0.156863
951         28  0.000008     1  ...                        NaN       NaN
952         28  0.000008     1  ...                        NaN       NaN
953         28  0.000008     1  ...                        NaN       NaN
954         28  0.000008     1  ...                       52.0  0.153846
955         28  0.000008     1  ...                        NaN       NaN
956         28  0.000008     1  ...                        NaN       NaN
957         28  0.000008     1  ...                        NaN       NaN
958         28  0.000008     1  ...                        NaN       NaN
959         28  0.000008     1  ...                        NaN       NaN
960         28  0.000008     1  ...                        NaN       NaN
961         28  0.000008     1  ...                        NaN       NaN
962         28  0.000008     1  ...                        NaN       NaN
963         28  0.000008     1  ...                        NaN       NaN
964         28  0.000008     1  ...                        NaN       NaN
965         28  0.000008     1  ...                        NaN       NaN
966         28  0.000008     1  ...                        NaN       NaN
5847        28  0.000008     1  ...                        NaN       NaN

     Simulated Annealing (T: 1000, CR: 0.9)                         \
                                       #ops      time  #sols prec.
947                                   685.0  0.000214  133.0   1.0
948                                     NaN       NaN    NaN   NaN
949                                     NaN       NaN    NaN   NaN
950                                   691.0  0.000224  133.0   1.0
951                                     NaN       NaN    NaN   NaN
952                                     NaN       NaN    NaN   NaN
953                                     NaN       NaN    NaN   NaN
954                                   676.0  0.000208  133.0   1.0
955                                     NaN       NaN    NaN   NaN
956                                     NaN       NaN    NaN   NaN
957                                     NaN       NaN    NaN   NaN
958                                     NaN       NaN    NaN   NaN
959                                     NaN       NaN    NaN   NaN
960                                     NaN       NaN    NaN   NaN
961                                     NaN       NaN    NaN   NaN
962                                     NaN       NaN    NaN   NaN
963                                     NaN       NaN    NaN   NaN
964                                     NaN       NaN    NaN   NaN
965                                     NaN       NaN    NaN   NaN
966                                     NaN       NaN    NaN   NaN
5847                                    NaN       NaN    NaN   NaN

     Random Greedy (IT: 0.01)
                         #ops      time #sols prec.
947                       NaN       NaN   NaN   NaN
948                       NaN       NaN   NaN   NaN
949                       NaN       NaN   NaN   NaN
950                       NaN       NaN   NaN   NaN
951                       NaN       NaN   NaN   NaN
952                       NaN       NaN   NaN   NaN
953                       NaN       NaN   NaN   NaN
954                       NaN       NaN   NaN   NaN
955                       NaN       NaN   NaN   NaN
956                       NaN       NaN   NaN   NaN
957                       NaN       NaN   NaN   NaN
958                       NaN       NaN   NaN   NaN
959                       NaN       NaN   NaN   NaN
960                       NaN       NaN   NaN   NaN
961                       NaN       NaN   NaN   NaN
962                       NaN       NaN   NaN   NaN
963                       NaN       NaN   NaN   NaN
964                       NaN       NaN   NaN   NaN
965                       NaN       NaN   NaN   NaN
966                       NaN       NaN   NaN   NaN
5847                     19.0  0.000014   5.0   1.0

[21 rows x 57 columns]

In [5]:
all_data

                      Graph                        Exhaustive             \
                       name      n      m   weight       #ops time #sols
0      graphs (gset)/G1.txt    800  19176  11624.0        NaN  NaN   NaN
1      graphs (gset)/G1.txt    800  19176  11624.0        NaN  NaN   NaN
2      graphs (gset)/G1.txt    800  19176  11624.0        NaN  NaN   NaN
3      graphs (gset)/G1.txt    800  19176  11624.0        NaN  NaN   NaN
4      graphs (gset)/G1.txt    800  19176  11624.0        NaN  NaN   NaN
...                     ...    ...    ...      ...        ...  ...   ...
6170   graphs (gset)/G7.txt    800  19176   2006.0        NaN  NaN   NaN
6171  graphs (gset)/G70.txt  10000   9999   9591.0        NaN  NaN   NaN
6172  graphs (gset)/G72.txt  10000  20000   7006.0        NaN  NaN   NaN
6173   graphs (gset)/G8.txt    800  19176   2005.0        NaN  NaN   NaN
6174   graphs (gset)/G9.txt    800  19176   2054.0        NaN  NaN   NaN

       Heuristic                   ... Random Solutions (MS: 100)            \
            #ops       time #sols  ...                        it. prec./it.
0        6225342   0.141065     1  ...                        NaN       NaN
1        6225342   0.141065     1  ...                        NaN       NaN
2        6225342   0.141065     1  ...                        NaN       NaN
3        6225342   0.141065     1  ...                        NaN       NaN
4        6225342   0.141065     1  ...                        NaN       NaN
...          ...        ...   ...  ...                        ...       ...
6170     6224765   0.143155     1  ...                        NaN       NaN
6171  1324406540  25.946424     1  ...                        NaN       NaN
6172  1324879857  26.921012     1  ...                        NaN       NaN
6173     6223580   0.144396     1  ...                        NaN       NaN
6174     6228653   0.140115     1  ...                        NaN       NaN

     Simulated Annealing (T: 1000, CR: 0.9)                   \
                                       #ops time #sols prec.
0                                       NaN  NaN   NaN   NaN
1                                       NaN  NaN   NaN   NaN
2                                       NaN  NaN   NaN   NaN
3                                       NaN  NaN   NaN   NaN
4                                       NaN  NaN   NaN   NaN
...                                     ...  ...   ...   ...
6170                                    NaN  NaN   NaN   NaN
6171                                    NaN  NaN   NaN   NaN
6172                                    NaN  NaN   NaN   NaN
6173                                    NaN  NaN   NaN   NaN
6174                                    NaN  NaN   NaN   NaN

     Random Greedy (IT: 0.01)
                         #ops time #sols prec.
0                         NaN  NaN   NaN   NaN
1                         NaN  NaN   NaN   NaN
2                         NaN  NaN   NaN   NaN
3                         NaN  NaN   NaN   NaN
4                         NaN  NaN   NaN   NaN
...                       ...  ...   ...   ...
6170                      NaN  NaN   NaN   NaN
6171                      NaN  NaN   NaN   NaN
6172                      NaN  NaN   NaN   NaN
6173                      NaN  NaN   NaN   NaN
6174                      NaN  NaN   NaN   NaN

[6175 rows x 57 columns]

In [6]:
df = all_data.sort_values(by=("Graph", "name"), ascending=True)
df = df.reset_index(drop=True)
df.to_excel("all_results1.xlsx")