In [4]:
import os
import pandas as pd

In [2]:
datas = [x for x in os.listdir() if "results_" in x and ".xlsx" in x]
datas

['results_1121171624.xlsx',
 'results_1121182007.xlsx',
 'results_1121184056.xlsx',
 'results_1121175757.xlsx',
 'results_1121180832.xlsx',
 'results_1121163732.xlsx',
 'results_1121184309.xlsx']

In [47]:
dfs = []
for data in datas:
    dfs.append(pd.read_excel(data, index_col=0, header=[0,1]))

all_data = pd.concat(dfs, ignore_index=True)

In [48]:
all_data[all_data[("Graph", "name")] == "graphs/0004_250.graphml"]

                        Graph              Exhaustive                  \
                         name  n  m weight       #ops      time #sols
1     graphs/0004_250.graphml  4  1   13.0       70.0  0.000023  16.0
330   graphs/0004_250.graphml  4  1   13.0       70.0  0.000023  16.0
659   graphs/0004_250.graphml  4  1   13.0       70.0  0.000023  16.0
988   graphs/0004_250.graphml  4  1   13.0       70.0  0.000023  16.0
1317  graphs/0004_250.graphml  4  1   13.0       70.0  0.000023  16.0
1646  graphs/0004_250.graphml  4  1   13.0       70.0  0.000023  16.0

     Heuristic                  ... Random Solutions (MS: 10000)            \
          #ops      time #sols  ...                          it. prec./it.
1           28  0.000008     1  ...                         42.0  0.190476
330         28  0.000008     1  ...                          NaN       NaN
659         28  0.000008     1  ...                         38.0  0.210526
988         28  0.000008     1  ...                          NaN       NaN
1317        28  0.000008     1  ...                          NaN       NaN
1646        28  0.000008     1  ...                          NaN       NaN

     Simulated Annealing (T: 1000, CR: 0.99)                          \
                                        #ops      time   #sols prec.
1                                     6897.0  0.002168  1376.0   1.0
330                                      NaN       NaN     NaN   NaN
659                                   6984.0  0.002197  1376.0   1.0
988                                      NaN       NaN     NaN   NaN
1317                                     NaN       NaN     NaN   NaN
1646                                     NaN       NaN     NaN   NaN

     Random Greedy (IT: 2)
                      #ops      time #sols prec.
1                     24.0  0.000008   6.0   1.0
330                    NaN       NaN   NaN   NaN
659                   24.0  0.000008   6.0   1.0
988                    NaN       NaN   NaN   NaN
1317                   NaN       NaN   NaN   NaN
1646                   NaN       NaN   NaN   NaN

[6 rows x 25 columns]

In [49]:
df_cleaned = all_data.dropna(thresh=len(all_data.columns) - 10)
df = df_cleaned.sort_values(by=("Graph", "name"), ascending=True)
df.reset_index(drop=True, inplace=True)

In [ ]:
#df.to_excel("all_results.xlsx")